service: tx-rooms

plugins:
    - serverless-offline
    - serverless-plugin-warmup

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-central-1
    stage: ${opt:stage, 'dev'}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - lambda:InvokeFunction
                  Resource: "*"
    environment:
        STAGE: ${file(./config/config.${self:provider.stage, 'dev'}.json):STAGE}
        SLACK_SIGNING_SECRET: ${file(./config/config.${self:provider.stage, 'dev'}.json):SLACK_SIGNING_SECRET}
        SLACK_VERIFICATION_TOKEN: ${file(./config/config.${self:provider.stage, 'dev'}.json):SLACK_VERIFICATION_TOKEN}
        SLACK_BOT_USER_OAUTH_ACCESS_TOKEN: ${file(./config/config.${self:provider.stage, 'dev'}.json):SLACK_BOT_USER_OAUTH_ACCESS_TOKEN}

package:
    exclude:
        - package.json
        - yarn.lock
        - coverage
        - __tests__
        - config
        - build/build-floors.js

functions:
    locate:
        handler: api/locate.locate
        warmup: true
        memorySize: 128
        events:
            - http:
                  path: locate
                  method: post
    interact:
        handler: api/interact.interact
        warmup: true
        memorySize: 128
        events:
            - http:
                  path: interact
                  method: post
    event:
        timeout: 30
        handler: api/event.event
        warmup: true
        memorySize: 128
        events:
            - http:
                  path: event
                  method: post
